# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_3/ip_0/bd_2647_vfb_0_0_axis_converter.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2647_vfb_0_0_axis_converter || ORIG_REF_NAME==bd_2647_vfb_0_0_axis_converter} -quiet] -quiet

# XDC: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_3/bd_2647_vfb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_2647_vfb_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_3/ip_0/bd_2647_vfb_0_0_axis_converter.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2647_vfb_0_0_axis_converter || ORIG_REF_NAME==bd_2647_vfb_0_0_axis_converter} -quiet] -quiet

# XDC: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_1_0/bd_0/ip/ip_3/bd_2647_vfb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_2647_vfb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
