# Master (100MHz) Clock N14
set_property PACKAGE_PIN N14 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK]

# USB
set_property PACKAGE_PIN P6 [get_ports {USB_BD[5]}]
set_property PACKAGE_PIN R7 [get_ports {USB_BD[3]}]
set_property PACKAGE_PIN R6 [get_ports {USB_BD[6]}]
set_property PACKAGE_PIN T5 [get_ports {USB_BC[0]}]
set_property PACKAGE_PIN R5 [get_ports {USB_BD[7]}]
set_property PACKAGE_PIN T10 [get_ports {USB_BC[3]}]
set_property PACKAGE_PIN T9 [get_ports {USB_SUS}]
set_property PACKAGE_PIN T8 [get_ports {USB_BD[2]}]
set_property PACKAGE_PIN T7 [get_ports {USB_BD[4]}]
set_property PACKAGE_PIN R8 [get_ports {USB_BD[1]}]
set_property PACKAGE_PIN P8 [get_ports {USB_BD[0]}]
set_property PACKAGE_PIN P9 [get_ports {USB_BC[1]}]
set_property PACKAGE_PIN N9 [get_ports {USB_BC[2]}]
set_property PACKAGE_PIN R11 [get_ports {USB_BC[6]}]
set_property PACKAGE_PIN R10 [get_ports {USB_BC[4]}]
set_property PACKAGE_PIN T12 [get_ports {USB_PWRSAV}]
set_property PACKAGE_PIN R12 [get_ports {USB_PWREN}]
set_property PACKAGE_PIN P10 [get_ports {USB_BC[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {USB_*}]

# RoboRIO
set_property PACKAGE_PIN C13 [get_ports {RIO_SDA}]
set_property PACKAGE_PIN E12 [get_ports {RIO_SCL}]
set_property IOSTANDARD LVCMOS33 [get_ports {RIO_*}]

# Config EEPROM
set_property PACKAGE_PIN E13 [get_ports {CONF_CLK}]
set_property PACKAGE_PIN E11 [get_ports {CONF_MOSI}]
set_property PACKAGE_PIN D11 [get_ports {CONF_HOLD}]
set_property PACKAGE_PIN D14 [get_ports {CONF_WP}]
set_property PACKAGE_PIN D15 [get_ports {CONF_MISO}]
set_property PACKAGE_PIN F12 [get_ports {CONF_CS}]
set_property IOSTANDARD LVCMOS33 [get_ports {CONF_*}]

# Flash Memory
set_property PACKAGE_PIN E8 [get_ports {FLASH_CLK}]
set_property PACKAGE_PIN L12 [get_ports {FLASH_CS}]
set_property PACKAGE_PIN K16 [get_ports {FLASH_SIO[3]}]
set_property PACKAGE_PIN K15 [get_ports {FLASH_SIO[2]}]
set_property PACKAGE_PIN J14 [get_ports {FLASH_SIO[1]}]
set_property PACKAGE_PIN J13 [get_ports {FLASH_SIO[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FLASH_*}]

# JTAG
set_property PACKAGE_PIN M7 [get_ports {TMS}]
set_property PACKAGE_PIN L7 [get_ports {TCK}]
set_property PACKAGE_PIN N8 [get_ports {TDO}]
set_property PACKAGE_PIN N7 [get_ports {TDI}]
set_property IOSTANDARD LVCMOS33 [get_ports {T*}]

# LEDs (0 = R, 1 = G, 2 = B)
set_property PACKAGE_PIN P5 [get_ports {LED_TAR[0]}]
set_property PACKAGE_PIN T3 [get_ports {LED_TAR[2]}]
set_property PACKAGE_PIN T4 [get_ports {LED_TAR[1]}]
set_property PACKAGE_PIN T2 [get_ports {LED_COM[0]}]
set_property PACKAGE_PIN R3 [get_ports {LED_COM[2]}]
set_property PACKAGE_PIN R1 [get_ports {LED_COM[1]}]
set_property PACKAGE_PIN A8 [get_ports {LED_PWR[0]}]
set_property PACKAGE_PIN A9 [get_ports {LED_PWR[2]}]
set_property PACKAGE_PIN B11 [get_ports {LED_PWR[1]}]
set_property PACKAGE_PIN B12 [get_ports {LED_EN[0]}]
set_property PACKAGE_PIN A12 [get_ports {LED_EN[2]}]
set_property PACKAGE_PIN A13 [get_ports {LED_EN[1]}]
set_property PACKAGE_PIN A14 [get_ports {LED_IR}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_*}]

# Power Data
set_property PACKAGE_PIN B14 [get_ports {PWR_V2UV}]
set_property PACKAGE_PIN B15 [get_ports {PWR_V1UV}]
set_property PACKAGE_PIN A15 [get_ports {PWR_V2ON}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_*}]

# Camera/Image Sensor LVDS
set_property PACKAGE_PIN F5 [get_ports {CAM_CLK_P}]
set_property PACKAGE_PIN E5 [get_ports {CAM_CLK_N}]
set_property PACKAGE_PIN F4 [get_ports {CAM_SYNC_P}]
set_property PACKAGE_PIN F3 [get_ports {CAM_SYNC_N}]
set_property PACKAGE_PIN F2 [get_ports {CAM_DOUT_P[3]}]
set_property PACKAGE_PIN E1 [get_ports {CAM_DOUT_N[3]}]
set_property PACKAGE_PIN G5 [get_ports {CAM_DOUT_P[2]}]
set_property PACKAGE_PIN G4 [get_ports {CAM_DOUT_N[2]}]
set_property PACKAGE_PIN G2 [get_ports {CAM_DOUT_P[1]}]
set_property PACKAGE_PIN G1 [get_ports {CAM_DOUT_N[1]}]
set_property PACKAGE_PIN H5 [get_ports {CAM_DOUT_P[0]}]
set_property PACKAGE_PIN H4 [get_ports {CAM_DOUT_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {CAM_CLK_P}]
set_property IOSTANDARD LVDS_25 [get_ports {CAM_CLK_N}]
set_property IOSTANDARD LVDS_25 [get_ports {CAM_SYNC_P}]
set_property IOSTANDARD LVDS_25 [get_ports {CAM_SYNC_N}]
set_property IOSTANDARD LVDS_25 [get_ports {CAM_DOUT_P}]
set_property IOSTANDARD LVDS_25 [get_ports {CAM_DOUT_N}]

# Camera/Image Sensor IO
set_property PACKAGE_PIN B16 [get_ports {CAM_SPI_CS}]
set_property PACKAGE_PIN C11 [get_ports {CAM_SPI_MOSI}]
set_property PACKAGE_PIN C12 [get_ports {CAM_SPI_MISO}]
set_property PACKAGE_PIN D13 [get_ports {CAM_SPI_CLK}]
set_property PACKAGE_PIN E16 [get_ports {CAM_TRIG[1]}]
set_property PACKAGE_PIN D16 [get_ports {CAM_TRIG[0]}]
set_property PACKAGE_PIN F15 [get_ports {CAM_MON[0]}]
set_property PACKAGE_PIN E15 [get_ports {CAM_TRIG[2]}]
set_property PACKAGE_PIN H16 [get_ports {CAM_RESET}]
set_property PACKAGE_PIN G16 [get_ports {CAM_MON[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAM_SPI_*}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAM_TRIG}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAM_MON}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAM_RESET}]