# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/MIPICSI2Reader/MIPICSI2Reader.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MIPICSI2Reader || ORIG_REF_NAME==MIPICSI2Reader} -quiet] -quiet

# IP: bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0 || ORIG_REF_NAME==MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0} -quiet] -quiet

# IP: bd/MIPICSI2Reader/ip/MIPICSI2Reader_v_axi4s_vid_out_0_0/MIPICSI2Reader_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MIPICSI2Reader_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==MIPICSI2Reader_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/MIPICSI2Reader/ip/MIPICSI2Reader_clk_wiz_0_0/MIPICSI2Reader_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MIPICSI2Reader_clk_wiz_0_0 || ORIG_REF_NAME==MIPICSI2Reader_clk_wiz_0_0} -quiet] -quiet

# XDC: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/MIPICSI2Reader_ooc.xdc
