# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.srcs/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0.xci
# IP: The module: 'MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/bd_0/bd_e616.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e616 || ORIG_REF_NAME==bd_e616} -quiet] -quiet

# IP: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_e616_r_sync_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e616_r_sync_0 || ORIG_REF_NAME==bd_e616_r_sync_0} -quiet] -quiet

# IP: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_e616_rx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e616_rx_0 || ORIG_REF_NAME==bd_e616_rx_0} -quiet] -quiet

# IP: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_e616_phy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e616_phy_0 || ORIG_REF_NAME==bd_e616_phy_0} -quiet] -quiet

# IP: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_e616_vfb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e616_vfb_0_0 || ORIG_REF_NAME==bd_e616_vfb_0_0} -quiet] -quiet

# XDC: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/bd_0/bd_e616_ooc.xdc

# XDC: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.srcs/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0.xci
# IP: The module: 'MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/bd_0/bd_e616.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e616 || ORIG_REF_NAME==bd_e616} -quiet] -quiet

# IP: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_e616_r_sync_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e616_r_sync_0 || ORIG_REF_NAME==bd_e616_r_sync_0} -quiet] -quiet

# IP: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_e616_rx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e616_rx_0 || ORIG_REF_NAME==bd_e616_rx_0} -quiet] -quiet

# IP: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_e616_phy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e616_phy_0 || ORIG_REF_NAME==bd_e616_phy_0} -quiet] -quiet

# IP: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_e616_vfb_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e616_vfb_0_0 || ORIG_REF_NAME==bd_e616_vfb_0_0} -quiet] -quiet

# XDC: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/bd_0/bd_e616_ooc.xdc

# XDC: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/liamsnow/Documents/GitHub/Virtex-Embedded-Code/Virtex-Embedded-Code.gen/sources_1/bd/MIPICSI2Reader/ip/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0/MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MIPICSI2Reader_mipi_csi2_rx_subsyst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
